extends:
  - eslint-config-airbnb-base
  - plugin:react/recommended
root: true

env:
  browser: true
  es6: true
  node: true

parserOptions:
  ecmaFeatures:
    jsx: true

rules:
  consistent-return:
    - 0
  no-underscore-dangle:
    - 0
  max-len:
    - 1
    - 100
  max-nested-callbacks:
    - 1
    - 4
  no-plusplus:
    - 0
  no-param-reassign:
    - 1
  class-methods-use-this:
    - 0
  import/no-extraneous-dependencies:
    - 1
  react/prefer-stateless-function:
   - 0
  react/forbid-prop-types:
    - 0
  react/jsx-filename-extension:
    - 0
  react/prop-types:
    - 0