version: '3'

services:

  db:
    image: wodby/postgres:9.6-1.1.0
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432-5433/tcp"

  web:
    build: './php'
    environment:
      # Change this to your actual local IP Address.
      XDEBUG_REMOTE_HOST: 10.12.3.38
    volumes:
      - web:/var/www
    labels:
      - 'traefik.backend=web'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:web.internal'

  mailhog:
    image: mailhog/mailhog
    environment:
      VIRTUAL_HOST: mailhog.internal
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.internal'

  traefik:
    image: traefik:1.6.6-alpine
    command: -c /dev/null --web --docker --logLevel=ERROR
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

#  nginx-proxy:
#    image: jwilder/nginx-proxy
#    ports:
#      - "80:80"
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro

volumes:
  db:
  web:
    driver: local
    driver_opts:
      type: none
      o: bind,delegated
      device: "$PWD"

networks:
  default:
